version: "3.9"  # optional since v1.27.0
services:
  api:
    container_name: flask-container
    build: .
    entrypoint: python3 app.py
    env_file:
      - .env
    ports:
      - '3000:3000'
  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"